package com.sun.sunclient.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF475d93)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFdae2ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001946)
val md_theme_light_secondary = Color(0xFF5a5e6c)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFdfe2f3)
val md_theme_light_onSecondaryContainer = Color(0xFF171b27)
val md_theme_light_tertiary = Color(0xFF6e576c)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFf8daf3)
val md_theme_light_onTertiaryContainer = Color(0xFF271527)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFfefbfe)
val md_theme_light_onBackground = Color(0xFF1b1b1e)
val md_theme_light_surface = Color(0xFFfefbfe)
val md_theme_light_onSurface = Color(0xFF1b1b1e)
val md_theme_light_surfaceVariant = Color(0xFFe2e2e9)
val md_theme_light_onSurfaceVariant = Color(0xFF45464c)
val md_theme_light_outline = Color(0xFF76777d)
val md_theme_light_inverseOnSurface = Color(0xFFEEF0FF)
val md_theme_light_inverseSurface = Color(0xFF002B75)
val md_theme_light_inversePrimary = Color(0xFFB1C5FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF385BA9)
val md_theme_light_outlineVariant = Color(0xFFC5C6D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB1C5FF)
val md_theme_dark_onPrimary = Color(0xFF152e62)
val md_theme_dark_primaryContainer = Color(0xFF2e457a)
val md_theme_dark_onPrimaryContainer = Color(0xFFdae2ff)
val md_theme_dark_secondary = Color(0xFFc2c6d6)
val md_theme_dark_onSecondary = Color(0xFF2c303d)
val md_theme_dark_secondaryContainer = Color(0xFF424654)
val md_theme_dark_onSecondaryContainer = Color(0xFFdfe2f3)
val md_theme_dark_tertiary = Color(0xFFdbbed7)
val md_theme_dark_onTertiary = Color(0xFF3d2a3d)
val md_theme_dark_tertiaryContainer = Color(0xFF554054)
val md_theme_dark_onTertiaryContainer = Color(0xFFf8daf3)
val md_theme_dark_error = Color(0xFFffb4ab)
val md_theme_dark_errorContainer = Color(0xFF93000a)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFffb4ab)
val md_theme_dark_background = Color(0xFF1b1b1e)
val md_theme_dark_onBackground = Color(0xFFe4e2e5)
val md_theme_dark_surface = Color(0xFF1b1b1e)
val md_theme_dark_onSurface = Color(0xFFe4e2e5)
val md_theme_dark_surfaceVariant = Color(0xFF45464c)
val md_theme_dark_onSurfaceVariant = Color(0xFFc6c6cd)
val md_theme_dark_outline = Color(0xFF909097)
val md_theme_dark_inverseOnSurface = Color(0xFF001849)
val md_theme_dark_inverseSurface = Color(0xFFDBE1FF)
val md_theme_dark_inversePrimary = Color(0xFF385BA9)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB1C5FF)
val md_theme_dark_outlineVariant = Color(0xFF44464F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF475d93)
val transparent = Color(0x00000000)